CREATE TABLE tester (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE tester_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER tester_trigger
BEFORE INSERT ON tester
FOR EACH ROW
BEGIN
    SELECT tester_seq.NEXTVAL INTO :new.id FROM dual;
END;
/